using System.Diagnostics;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddDbContext<TaskDb>(options =>
    options.UseSqlite(builder.Configuration.GetConnectionString("Tasks") ?? "Data Source=data/tasks.db"));

var app = builder.Build();

app.UseExceptionHandler(error => error.Run(async context =>
{
    context.Response.StatusCode = StatusCodes.Status500InternalServerError;
    await context.Response.WriteAsJsonAsync(new { error = "The request failed intentionally or unexpectedly." });
}));

Directory.CreateDirectory("data");
await using (var scope = app.Services.CreateAsyncScope())
{
    var db = scope.ServiceProvider.GetRequiredService<TaskDb>();
    await db.Database.EnsureCreatedAsync();
}

app.MapGet("/health", () => Results.Ok(new { status = "ok" }));

var tasks = app.MapGroup("/tasks/api");

tasks.MapPost("/", async (TaskItem input, TaskDb db, ILogger<Program> log) =>
{
    input.Id = 0;
    input.CreatedAt = DateTimeOffset.UtcNow;
    db.Tasks.Add(input);
    await db.SaveChangesAsync();
    Telemetry.Requests.Add(1, new KeyValuePair<string, object?>("task.operation", "create"));
    log.LogInformation("Created task {TaskId}", input.Id);
    return Results.Created($"/tasks/api/{input.Id}", input);
});

tasks.MapGet("/", async (bool fail, TaskDb db) =>
{
    if (fail) throw new InvalidOperationException("Intentional task list failure");
    return Results.Ok(await db.Tasks.AsNoTracking().OrderByDescending(t => t.Id).ToListAsync());
});

tasks.MapGet("/{id:long}", async (long id, TaskDb db) =>
    await db.Tasks.AsNoTracking().FirstOrDefaultAsync(t => t.Id == id) is { } task
        ? Results.Ok(task)
        : Results.NotFound(new { error = $"Task {id} not found" }));

tasks.MapPut("/{id:long}", async (long id, TaskItem input, TaskDb db) =>
{
    var task = await db.Tasks.FindAsync(id);
    if (task is null) return Results.NotFound(new { error = $"Task {id} not found" });
    task.Title = input.Title;
    task.Description = input.Description;
    task.Completed = input.Completed;
    await db.SaveChangesAsync();
    return Results.Ok(task);
});

tasks.MapDelete("/{id:long}", async (long id, TaskDb db) =>
{
    var task = await db.Tasks.FindAsync(id);
    if (task is null) return Results.NotFound(new { error = $"Task {id} not found" });
    db.Tasks.Remove(task);
    await db.SaveChangesAsync();
    return Results.NoContent();
});

tasks.MapGet("/test/bad-query", async (bool fail, TaskDb db) =>
{
    if (!fail) return Results.Ok(new { message = "Bad query skipped" });
    using var activity = Telemetry.ActivitySource.StartActivity("taskdb.bad-query", ActivityKind.Client);
    activity?.SetTag("db.system", "sqlite");
    activity?.SetTag("db.operation.name", "SELECT");
    try
    {
        await db.Database.ExecuteSqlRawAsync("SELECT * FROM non_existent_table WHERE invalid_column = 'test'");
        return Results.Ok();
    }
    catch (Exception ex)
    {
        activity?.SetStatus(ActivityStatusCode.Error, ex.Message);
        activity?.AddEvent(new ActivityEvent("exception", tags: new ActivityTagsCollection
        {
            ["exception.type"] = ex.GetType().FullName,
            ["exception.message"] = ex.Message,
            ["exception.stacktrace"] = ex.StackTrace
        }));
        throw;
    }
});

tasks.MapGet("/test/slow-db-read", async (long delayMs, long dbDelayMs, TaskDb db) =>
{
    (delayMs, dbDelayMs) = NormalizeDelays(delayMs, dbDelayMs);
    long count;
    using (var activity = StartDbActivity("taskdb.slow-read", "SELECT"))
    {
        count = await db.Tasks.LongCountAsync();
        await Task.Delay((int)dbDelayMs);
    }
    await Task.Delay((int)(delayMs - dbDelayMs));
    return Results.Ok(new { type = "slow-db-read", delayMs, dbDelayMs, taskCount = count });
});

tasks.MapGet("/test/slow-db-write", async (long delayMs, long dbDelayMs, TaskDb db) =>
{
    (delayMs, dbDelayMs) = NormalizeDelays(delayMs, dbDelayMs);
    long count;
    using (var activity = StartDbActivity("taskdb.slow-write", "INSERT/DELETE"))
    {
        var task = new TaskItem { Title = "slow-load-task", Description = "Generated by slow load endpoint" };
        db.Tasks.Add(task);
        await db.SaveChangesAsync();
        count = await db.Tasks.LongCountAsync();
        await Task.Delay((int)dbDelayMs);
        db.Tasks.Remove(task);
        await db.SaveChangesAsync();
    }
    await Task.Delay((int)(delayMs - dbDelayMs));
    return Results.Ok(new { type = "slow-db-write", delayMs, dbDelayMs, taskCount = count });
});

app.Run();

static (long delayMs, long dbDelayMs) NormalizeDelays(long delayMs, long dbDelayMs)
{
    delayMs = Math.Clamp(delayMs == 0 ? 1200 : delayMs, 1100, 10_000);
    dbDelayMs = Math.Clamp(dbDelayMs == 0 ? 600 : dbDelayMs, 600, delayMs);
    return (delayMs, dbDelayMs);
}

static Activity? StartDbActivity(string name, string operation)
{
    var activity = Telemetry.ActivitySource.StartActivity(name, ActivityKind.Client);
    activity?.SetTag("db.system", "sqlite");
    activity?.SetTag("db.operation.name", operation);
    return activity;
}

public sealed class TaskDb(DbContextOptions<TaskDb> options) : DbContext(options)
{
    public DbSet<TaskItem> Tasks => Set<TaskItem>();
}

public sealed class TaskItem
{
    public long Id { get; set; }
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
    public bool Completed { get; set; }
    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;
}

public static class Telemetry
{
    public const string SourceName = "TaskManager.Api";
    public const string MeterName = "TaskManager.Api";
    public static readonly ActivitySource ActivitySource = new(SourceName);
    public static readonly System.Diagnostics.Metrics.Meter Meter = new(MeterName);
    public static readonly System.Diagnostics.Metrics.Counter<long> Requests = Meter.CreateCounter<long>("task.operations");
}

public partial class Program;
