# # OpenTelemetry Configuration
# otel.service.name=task-manager
# otel.traces.exporter=logging
# otel.metrics.exporter=logging
# otel.logs.exporter=logging

# # Sampling configuration
# otel.traces.sampler=parentbased_always_on

# # Resource attributes
# otel.resource.attributes=service.version=1.0.0,deployment.environment=development 

# OpenTelemetry Configuration
otel.service.name=task-manager
otel.traces.exporter=otlp
otel.metrics.exporter=otlp
otel.logs.exporter=otlp

# Sampling configuration
otel.traces.sampler=parentbased_always_on

# Resource attributes
otel.resource.attributes=service.version=1.0.0,deployment.environment=development

# OTLP Metrics Endpoint
otel.exporter.otlp.endpoint=http://demo.codexray.io:9090/api/v1/otlp/v1/metrics
otel.exporter.otlp.traces.endpoint=http://demo.codexray.io/v1/traces
otel.exporter.otlp.logs.endpoint=http://demo.codexray.io/v1/logs