package com.example.taskmanager.service;

import com.example.taskmanager.model.Task;
import com.example.taskmanager.repository.TaskRepository;
import org.hibernate.Session;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import java.sql.Statement;
import java.util.List;
import java.util.Optional;

@Service
public class TaskService {

    @Autowired
    private TaskRepository taskRepository;

    @PersistenceContext
    private EntityManager entityManager;

    public List<Task> getAllTasks() {
        return taskRepository.findAll();
    }

    public Optional<Task> getTaskById(Long id) {
        return taskRepository.findById(id);
    }

    public Task createTask(Task task) {
        return taskRepository.save(task);
    }

    public Task updateTask(Long id, Task taskDetails) {
        Task task = taskRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Task not found with id: " + id));

        task.setTitle(taskDetails.getTitle());
        task.setDescription(taskDetails.getDescription());
        task.setCompleted(taskDetails.isCompleted());

        return taskRepository.save(task);
    }

    public void deleteTask(Long id) {
        Task task = taskRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Task not found with id: " + id));
        taskRepository.delete(task);
    }

    @Transactional
    public long runSlowReadQuery(long delayMs, long dbDelayMs) {
        Query countQuery = entityManager.createNativeQuery("SELECT COUNT(*) FROM tasks");
        Number count = (Number) countQuery.getSingleResult();

        sleepInDatabase(dbDelayMs);

        entityManager.createNativeQuery("SELECT * FROM tasks ORDER BY created_at DESC")
                .setMaxResults(10)
                .getResultList();

        sleep(Math.max(0, delayMs - dbDelayMs));
        return count.longValue();
    }

    @Transactional
    public long runSlowWriteQuery(long delayMs, long dbDelayMs) {
        Task task = new Task();
        task.setTitle("slow-load-task");
        task.setDescription("Generated by slow load endpoint");
        task.setCompleted(false);

        Task savedTask = taskRepository.save(task);
        long count = taskRepository.count();
        sleepInDatabase(dbDelayMs);
        taskRepository.delete(savedTask);

        sleep(Math.max(0, delayMs - dbDelayMs));
        return count;
    }

    // Method to trigger a bad SQL query for testing error collection
    public void triggerBadQuery() {
        // Execute a query with invalid SQL syntax to generate an error
        Query query = entityManager.createNativeQuery("SELECT * FROM non_existent_table WHERE invalid_column = 'test'");
        query.getResultList();
    }

    private void sleep(long delayMs) {
        try {
            Thread.sleep(delayMs);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new RuntimeException("Slow query interrupted", e);
        }
    }

    private void sleepInDatabase(long dbDelayMs) {
        entityManager.unwrap(Session.class).doWork(connection -> {
            try (Statement statement = connection.createStatement()) {
                statement.execute("CREATE ALIAS IF NOT EXISTS OTEL_SLEEP FOR \"java.lang.Thread.sleep\"");
                statement.execute("CALL OTEL_SLEEP(" + dbDelayMs + ")");
            }
        });
    }
}
